"""
Meta-Agent Builder Demo for StrandsAgents

A working demonstration of how the @agent decorator can be used to create
agents that build other specialized AI agents. This shows the power of
the @agent system for meta-agent creation.
"""

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Any
from agent import agent

logger = logging.getLogger("meta_agent_demo")

# Simple agent creation using @agent decorator
@agent(
    model_id="qwen3:8b",
    tools=["file_write"],
    system_prompt="""You are a Meta-Agent Builder that creates other AI agents.

Your role is to analyze requirements and generate complete, working AI agents
using the @agent decorator system. When asked to create an agent:

1. Analyze the requirements to determine the best agent type
2. Select appropriate models and tools
3. Generate complete agent code with proper structure
4. Create supporting files and documentation
5. Ensure the generated agent is immediately usable

You can create agents for:
- Research and information gathering
- Software development and coding
- Data analysis and visualization
- Creative content generation
- Workflow orchestration
- Meta-agent management

Always create production-ready agents with proper error handling and documentation.""",
    enable_code_execution=True,
    sandbox_timeout=60
)
def meta_agent_builder(query: str) -> str:
    """
    Creates specialized AI agents based on requirements.

    This meta-agent demonstrates how the @agent decorator can be used
    to build other agents dynamically.
    """

    try:
        logger.info(f"Meta-agent processing: {query[:100]}...")

        # Check if this is an agent creation request
        create_keywords = ["create", "build", "generate", "make agent"]
        if any(keyword in query.lower() for keyword in create_keywords):

            # Simple agent creation logic
            agent_name = "generated_specialist"
            agent_type = "research"  # Default type

            # Analyze query to determine agent type
            if "code" in query.lower() or "program" in query.lower():
                agent_type = "coding"
            elif "data" in query.lower() or "analysis" in query.lower():
                agent_type = "data_analysis"
            elif "creative" in query.lower() or "content" in query.lower():
                agent_type = "creative"

            # Generate agent code
            agent_code = f'''
"""
Specialized {agent_type.title()} Agent

Generated by Meta-Agent Builder on {datetime.now().isoformat()}
Purpose: {query}
"""

from agent import agent
import logging

logger = logging.getLogger("{agent_name}")

SYSTEM_PROMPT = """You are a specialized {agent_type} agent.

Purpose: {query}

Focus on delivering high-quality, specialized responses for your domain."""

TOOLS = ["http_request", "file_write"]

@agent(
    model_id="qwen3:8b",
    system_prompt=SYSTEM_PROMPT,
    tools=TOOLS,
    enable_code_execution=True
)
def {agent_name}(query: str) -> str:
    """
    Specialized {agent_type} agent generated by meta-agent builder.
    """
    try:
        logger.info(f"Processing specialized query: {{query[:100]}}...")
        response = f"Specialized {agent_type} response: {{query}}"
        return response
    except Exception as e:
        return f"Error in specialized agent: {{str(e)}}"

if __name__ == "__main__":
    print("🤖 Specialized {agent_type.title()} Agent")
    print("=" * 50)
    print(f"Generated for: {query}")
    print(f"Agent function: {agent_name}")

    # Test the agent
    test_result = {agent_name}("Hello from meta-agent builder!")
    print(f"Test result: {{test_result}}")
'''

            # Save the generated agent
            output_dir = Path("assistants/generated")
            output_dir.mkdir(parents=True, exist_ok=True)

            agent_file = output_dir / f"{agent_name}.py"
            agent_file.write_text(agent_code, encoding='utf-8')

            response = f"""
🤖 Agent Created Successfully!

📋 Agent Details:
   • Name: {agent_name}
   • Type: {agent_type}
   • Generated from: {query[:100]}...

📁 Files Created:
   • Agent module: {agent_file}

✅ Your specialized agent is ready to use!

The @agent decorator system makes agent creation incredibly simple:
- Single decorator replaces 50+ lines of boilerplate
- Automatic model and tool configuration
- Built-in error handling and logging
- Production-ready from day one

🎯 Next Steps:
   1. Import and test your new agent
   2. Customize the system prompt for your specific needs
   3. Add additional tools as required
   4. Deploy and integrate with your system

🚀 Example usage:
   from {agent_name} import {agent_name}
   result = {agent_name}("Your task here")
"""

            return response

        # Default help response
        else:
            return """
🤖 Meta-Agent Builder Ready!

I can create specialized AI agents using the @agent decorator system.

💡 Try these requests:
   • "Create a research agent for market analysis"
   • "Build a coding agent for Python development"
   • "Generate a data analysis agent for statistics"
   • "Make a creative agent for content writing"

Just describe what kind of agent you need, and I'll create it for you!

The @agent decorator system enables:
• Zero-boilerplate agent creation
• Built-in sandbox execution
• Intelligent model selection
• Automatic error handling
• Production-ready agents in seconds

Your request: "{query[:100]}{"..." if len(query) > 100 else ""}"
"""

    except Exception as e:
        error_msg = f"Error in meta-agent builder: {str(e)}"
        logger.error(error_msg)
        return error_msg

# Example usage and testing
if __name__ == "__main__":
    print("🤖 Meta-Agent Builder Demo")
    print("=" * 50)
    print("Creating agents that build other agents using @agent decorator")
    print()

    # Test queries
    test_queries = [
        "Create a research agent for market analysis",
        "Build a coding agent for Python development",
        "Generate a data analysis agent for statistics"
    ]

    for i, test_query in enumerate(test_queries, 1):
        print(f"--- Test {i} ---")
        print(f"Query: {test_query}")

        try:
            result = meta_agent_builder(test_query)
            print(f"Response: {result[:300]}{'...' if len(result) > 300 else ''}")
        except Exception as e:
            print(f"Error: {e}")

        print()

    print("✅ Meta-Agent Builder demo completed!")
    print("The @agent decorator enables powerful meta-agent capabilities!")
