#!/usr/bin/env python3
"""
Docker_Test_Agent Agent

An agent for testing Docker deployment

Generated by Working Agent Builder
Runtime: ollama
Model: llama3.2
"""

import sys
import os
import logging
import json
import requests
from typing import Optional, List
from datetime import datetime

# Setup logging
logger = logging.getLogger("docker_test_agent")

# Add current directory to path for relative imports
current_dir = os.path.dirname(os.path.abspath(__file__))
if current_dir not in sys.path:
    sys.path.insert(0, current_dir)


class SimpleAgent:
    """Simple working agent implementation"""

    def __init__(self, model_id: str = "llama3.2", system_prompt: str = ""):
        self.model_id = model_id
        self.system_prompt = system_prompt or "You are a helpful AI assistant."

    def __call__(self, query: str) -> str:
        """Process a query"""
        try:
            if "ollama" == "ollama":
                return self._call_ollama(query)
            else:
                return self._call_bedrock(query)
        except Exception as e:
            return f"Agent error: {str(e)}"

    def _call_ollama(self, query: str) -> str:
        """Call Ollama API"""
        try:
            response = requests.post(
                "http://localhost:11434/api/chat",
                json={
                    "model": self.model_id,
                    "messages": [
                        {"role": "system", "content": self.system_prompt},
                        {"role": "user", "content": query}
                    ],
                    "stream": False
                },
                timeout=60
            )
            response.raise_for_status()
            result = response.json()
            return result["message"]["content"]
        except Exception as e:
            return f"Ollama API error: {str(e)}"

    def _call_bedrock(self, query: str) -> str:
        """Call AWS Bedrock API"""
        try:
            import boto3

            client = boto3.client("bedrock-runtime")
            response = client.invoke_model(
                modelId=self.model_id,
                body=json.dumps({
                    "anthropic_version": "bedrock-2023-05-31",
                    "max_tokens": 1000,
                    "messages": [
                        {"role": "human", "content": query}
                    ]
                })
            )

            result = json.loads(response["body"].read())
            return result["content"][0]["text"]
        except Exception as e:
            return f"Bedrock API error: {str(e)}"


# Create agent instance
agent_instance = SimpleAgent(
    model_id="llama3.2",
    system_prompt="""You are docker_test_agent, a specialized AI agent.

An agent for testing Docker deployment

Focus on delivering high-quality, accurate responses for your domain."""
)


def docker_test_agent(query: str) -> str:
    """
    An agent for testing Docker deployment

    Args:
        query: Input query or request

    Returns:
        Response from the agent
    """
    try:
        agent_name = AGENT_METADATA.get("name", "docker_test_agent")
        logger.info(f"{agent_name.title()} processing query: {query[:100]}...")

        # Add agent-specific logic here
        response = agent_instance(query)

        logger.info(f"{agent_name.title()} completed successfully")
        return response

    except Exception as e:
        agent_name = AGENT_METADATA.get("name", "docker_test_agent")
        error_msg = f"Error in {agent_name}: {str(e)}"
        logger.error(error_msg)
        return error_msg


# Agent metadata
AGENT_METADATA = {
    "name": "docker_test_agent",
    "description": "An agent for testing Docker deployment",
    "model": "llama3.2",
    "runtime": "ollama",
    "created_at": "2025-10-10T23:31:52.469729",
    "version": "1.0.0"
}


if __name__ == "__main__":
    print("Docker_Test_Agent Agent")
    print("=" * 50)
    print(f"Description: {AGENT_METADATA['description']}")
    print(f"Model: {AGENT_METADATA['model']}")
    print(f"Runtime: {AGENT_METADATA['runtime']}")
    print()

    # Test the agent
    test_query = "Hello, please demonstrate your capabilities"
    print(f"Test Query: {test_query}")
    print()

    try:
        result = docker_test_agent(test_query)
        print(f"Response: {result}")
        print("SUCCESS: Agent working correctly!")
    except Exception as e:
        print(f"❌ Agent test failed: {e}")
        import traceback
        traceback.print_exc()
